### ISSUE TITLE
Adding CODECOV token explicitly to avoid issues with the github actions

### ISSUE THREAD

**Issue by JPchico** [aiidaplugins/aiida-lammps#62]
Apparently in the new github action one needs to explicitly pass a CODECOV token to avoid having an error when trying to get the coverage, even when one is in a public open source repo. To solve this one needs to put in the CODECOV token as an env variable in the CI/CD.

**Comment by JPchico** [comment]
@chrisjsewell I think that the random failures that are being experienced in the upload to codecov tests can be solved if [one stores the token as a secret and then passes it in the action](https://github.com/codecov/codecov-action/issues/557) as
```yaml
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
```
I have tested on my fork and it seems to work fine. I'll make a PR with the changes but I need to make sure that the aiida-lammps codecov secret is stored as `CODECOV_TOKEN` in the secrets of the action and I do not have permissions to do that. So if you can check that it would be great!
